name: google-analytics-action
description: Inject Google Analytics tracking code into an HTML file with GitHub Actions
author: remarkablemark

inputs:
  html-file:
    description: Path to the HTML file to modify
    required: true

  measurement-id:
    description: Google Analytics Measurement ID (e.g., G-XXXXXXXXXX)
    required: true

runs:
  using: composite
  steps:
    - name: Inject Google Analytics script
      shell: bash
      run: |
        # TODO
      env:
        VERSION: ${{ inputs.version }}

branding:
  icon: bar-chart
  color: orange
